### ISSUE TITLE
feat: Add scrollable game history with status indicators

### ISSUE THREAD

**Issue by portdeveloper** [portdeveloper/slot-machine-monorepo#11]
Create a game history section showing recent game results.

Technical Requirements:
- Implement scrollable container
- Add history entries with:
  - Win/Loss status (green/pink)
  - Timestamp
  - Number of matches
  - Points earned
- Limit history length for performance

**Comment by aslanw3b** [comment]
last spin results have been added at the bottom of the page.
the most recent 18 game history is now available. More or less can be done

![image](https://github.com/user-attachments/assets/2f757712-2c76-45cd-af3c-3122961080b3)

**Comment by caginagirdemir** [comment]
- Implement scrollable container ✅
- Add history entries with:
  - Win/Loss status (green/pink) ✅
  - Timestamp ✅
  - Number of matches ✅
  - Points earned ✅
- Limit history length for performance ✅
- Phone screen responsive ✅

![image](https://github.com/user-attachments/assets/9a8f3db5-cfa2-45b5-93b4-bf4c52e09fb9)

![127 0 0 1_5500_packages_frontend_index html(iPhone 12 Pro)](https://github.com/user-attachments/assets/fb6a9d9f-e924-4232-950b-b5d413d32f67)
