### ISSUE TITLE
Page layout for non-logged-in users

### ISSUE THREAD

**Issue by aslanw3b** [portdeveloper/slot-machine-monorepo#13]
Login with Telegram button (top left)
Disabled slot machine
Credits, points and score will appear as zero
A text telling visitors to log in to start the game

Check;
https://www.figma.com/proto/3rGiuOYd1jtnrLyNSGuYw9/Slot-Machine?page-id=0%3A1&node-id=275-317&node-type=frame&viewport=-1091%2C1525%2C0.4&t=TN6OzPkS0A388BhW-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3%3A692

**Comment by caginagirdemir** [comment]
Hi, I'd like to work on this issue. Could you assign it to me?
