### ISSUE TITLE
issue: Missing .gitignore

### ISSUE THREAD

**Issue by aurelien-cuvelier** [portdeveloper/slot-machine-monorepo#2]
### Is there an existing issue for this?

- [X] I have looked through the existing issues

### Current Behavior

When installing dependencies with your package manager, node_modules are getting caught in the commits. Potential .env files are also impacted by that.

### Expected Behavior

node_modules on all the 3 level of dependencies (/ ; packages/backend ; packages/fontend) should not be added to the commits, neither any potential .env file.

### Steps To Reproduce

npm install

**Comment by portdeveloper** [comment]
solved at #3
